name: WebAssembly

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
  
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.0.0
          actions-cache-folder: 'emsdk-cache'
      - name: build raylib
        run: |
          cd ..
          git clone https://github.com/raysan5/raylib 
          cd raylib/src
          make PLATFORM=PLATFORM_WEB EMSDK_PATH="D:/a/planet-clash/planet-clash/emsdk-cache/emsdk-main" -B
      - name: build
        run: |
          cd src
          make PLATFORM=PLATFORM_WEB EMSDK_PATH="D:/a/planet-clash/planet-clash/emsdk-cache/emsdk-main"
          dir
      - name: copy files
        run: |
          cd src
          mkdir output
          mv raylib_game.data output
          mv raylib_game.html output/index.html
          mv raylib_game.js output
          mv raylib_game.wasm output
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: ./src/output
